In [117]:
import pandas as pd
import numpy as np

In [ ]:
#Import databases 
from google.colab import files
uploaded = files.upload()

Saving Evolution de humidité relative maximale dans les principales stations des régions.xlsx to Evolution de humidité relative maximale dans les principales stations des régions (3).xlsx
Saving Evolution de la durée moyenne journalières insolation dans les principales stations des régions.xlsx to Evolution de la durée moyenne journalières insolation dans les principales stations des régions (3).xlsx
Saving Evolution de la production par région et type de céréale.xlsx to Evolution de la production par région et type de céréale (3).xlsx
Saving Evolution de la superficie par région et type de céréale.xlsx to Evolution de la superficie par région et type de céréale (3).xlsx
Saving Evolution de la vitesse moyenne du vent dans les principales stations des régions.xlsx to Evolution de la vitesse moyenne du vent dans les principales stations des régions (3).xlsx
Saving Evolution des hauteurs de pluie annuelle dans les principales stations mm.xlsx to Evolution des hauteurs de pluie annuelle dans les principales stations mm (3).xlsx
Saving Evolution des températures dans les principales stations des régions.xlsx to Evolution des températures dans les principales stations des régions (3).xlsx
Saving Evolution du nombre annuel de jours de pluie dans les principales stations des régions.xlsx to Evolution du nombre annuel de jours de pluie dans les principales stations des régions (3).xlsx

In [ ]:
# Load databases
df_prod = pd.read_excel('Evolution de la production par région et type de céréale.xlsx', skiprows=6)
df_superf = pd.read_excel('Evolution de la superficie par région et type de céréale.xlsx', skiprows=6)
df_precip = pd.read_excel('Evolution des hauteurs de pluie annuelle dans les principales stations mm.xlsx', skiprows=6)
df_pluie = pd.read_excel('Evolution du nombre annuel de jours de pluie dans les principales stations des régions.xlsx', skiprows=6)
df_temp = pd.read_excel('Evolution des températures dans les principales stations des régions.xlsx', skiprows=6)
df_humid = pd.read_excel('Evolution de humidité relative maximale dans les principales stations des régions.xlsx')
df_vent = pd.read_excel('Evolution de la vitesse moyenne du vent dans les principales stations des régions.xlsx', skiprows=6)
df_soleil = pd.read_excel('Evolution de la durée moyenne journalières insolation dans les principales stations des régions.xlsx', skiprows=6)

In [ ]:
# Verify columns
print(df_prod.columns)
print(df_superf.columns)
print(df_precip.columns)
print(df_pluie.columns)
print(df_temp.columns)
print(df_humid.columns)
print(df_vent.columns)
print(df_soleil.columns)

Index(['Région', 'Céréales', 'Units', '1996', '1997', '1998', '1999', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020', '2021', '2022'],
      dtype='object')
Index(['Région', 'Céréales', 'Units', '1996', '1997', '1998', '1999', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020', '2021', '2022'],
      dtype='object')
Index(['Région', 'Units', '1996', '1997', '1998', '1999', '2000', '2001',
       '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010',
       '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020', '2021', '2022'],
      dtype='object')
Index(['Région', 'Units', '1996', '1997', '1998', '1999', '2000', '2001',
       '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010',
       '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020', '2021', '2022'],
      dtype='object')
Index(['Région', 'Units', '1996', '1997', '1998', '1999', '2000', '2001',
       '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010',
       '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020', '2021', '2022'],
      dtype='object')
Index(['Région', '1996', '1997', '1998', '1999', '2000', '2001', '2002',
       '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020',
       '2021', '2022'],
      dtype='object')
Index(['Région', 'Units', '1996', '1997', '1998', '1999', '2000', '2001',
       '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010',
       '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020', '2021', '2022'],
      dtype='object')
Index(['Région', 'Units', '1996', '1997', '1998', '1999', '2000', '2001',
       '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010',
       '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020', '2021', '2022'],
      dtype='object')

In [ ]:
#Visualization of bases and structures
df_prod.head()

,Région,Céréales,Units,1996,1997,1998,1999,2000,2001,2002,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Burkina Faso,Arachide,tonne,180532,220534,152128,214807,282754,169146,301092,...,310758,349688,335222,365887,515672,334328,329783,396129,6.305258e+05,4.772543e+05
1,Burkina Faso,Coton,tonne,150451,202630,343106,324557,257121,212545,395031,...,606206,766221,894982,768930,774380,844343,482173,724232,6.966356e+05,6.807668e+05
2,Burkina Faso,Maïs,tonne,212493,293707,366467,377758,468948,315773,606291,...,1556315,1585418,1422830,1469611,1602525,1533431,1700127,1710898,1.920101e+06,1.853510e+06
3,Burkina Faso,Mil,tonne,733704,811497,603932,972768,945001,604153,1009044,...,1078374,1078570,972539,946184,905071,828234,1189079,970176,9.572530e+05,7.053450e+05
4,Burkina Faso,Niebé,tonne,195444,254157,183077,338102,309466,127682,376225,...,598525,599804,562729,571304,558925,555833,683174,707994,7.045395e+05,4.548405e+05

In [122]:
df_superf.head()

,Région,Céréales,Units,1996,1997,1998,1999,2000,2001,2002,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Burkina Faso,Arachide,ha,274349,211552,232663,215160,271469,236880,330904,...,397762,448767,375039,432665,585302,554832,394031,485703,6.707980e+05,6.463028e+05
1,Burkina Faso,Coton,ha,145418,200768,276911,334770,211931,209113,345578,...,531242,629460,651294,657840,645303,844895,473375,590999,5.666351e+05,6.113249e+05
2,Burkina Faso,Maïs,ha,185731,189235,241333,271405,288745,241401,334682,...,846490,913630,749935,820117,911728,956386,1019181,1014907,1.089389e+06,1.218764e+06
3,Burkina Faso,Mil,ha,1019406,1078118,1154596,1243853,1283701,1138581,1322953,...,1272901,1327078,1192007,1160718,1187397,1222575,1393878,1176512,1.065735e+06,9.763350e+05
4,Burkina Faso,Niebé,ha,14152,14281,23190,33976,35709,27098,47224,...,133522,167196,168338,165647,229548,293517,378942,339620,2.977555e+05,3.614705e+05

In [123]:
df_pluie.head()

,Région,Units,1996,1997,1998,1999,2000,2001,2002,2003,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Hauts-Bassins,Nombre,84.0,86.0,93.0,99.0,95.0,87.0,82.0,95.0,...,89.0,101.0,80,85,76,100,96,88,97,100.0
1,Centre-Est,Nombre,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.0,68.0,51,62,46,45,48,54,47,55.0
2,Centre-Nord,Nombre,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,44.0,46.0,42,38,29,42,36,42,40,46.0
3,Boucle du Mouhoun,Nombre,66.0,67.0,75.0,87.0,68.0,73.0,61.0,86.0,...,65.0,76.0,68,71,68,74,72,76,72,74.0
4,Sahel,Nombre,39.0,52.0,52.0,50.0,48.0,43.0,47.0,56.0,...,49.0,42.0,42,46,46,49,50,58,48,NaN

In [124]:
df_precip.head()

,Région,Units,1996,1997,1998,1999,2000,2001,2002,2003,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Hauts-Bassins,mm/an,900.5,872.9,1122.9,1066.2,1171.7,924.5,807.6,1155.7,...,936.2,1277.9,1155.4,1190.6,681.7,1320.5,1402.0,1131.5,1219.1,1233.9
1,Centre-Est,mm/an,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,642.6,862.1,700.6,1049.6,659.2,725.0,796.5,900.6,836.7,1066.9
2,Centre-Nord,mm/an,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,786.0,764.0,708.0,882.0,545.0,933.0,583.0,867.2,611.0,907.0
3,Boucle du Mouhoun,mm/an,676.0,837.9,945.3,921.9,580.7,811.7,744.8,986.0,...,749.2,798.4,1148.2,808.0,865.8,834.8,901.9,826.7,826.8,889.0
4,Sahel,mm/an,354.1,532.4,508.4,552.0,356.1,400.8,432.9,753.2,...,579.3,432.0,530.9,519.2,531.5,493.5,568.9,826.1,557.3,NaN

In [125]:
df_vent.head()

,Région,Units,1996,1997,1998,1999,2000,2001,2002,2003,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Hauts-Bassins,m/s,3.2,3.3,3.4,2.7,3.1,3.3,3.4,3.1,...,3.1,3.0,3.0,2.9,2.8,2.7,2.8,2.858333,2.8,2.9
1,Boucle du Mouhoun,m/s,2.3,2.4,2.4,2.6,2.7,2.2,2.1,1.8,...,3.0,2.6,2.7,1.8,1.9,2.3,2.5,2.366667,2.3,2.3
2,Sahel,m/s,1.4,1.4,1.4,1.2,1.5,1.6,1.5,1.3,...,0.9,0.9,0.9,1.0,1.8,0.9,0.8,0.775000,1.0,NaN
3,Est,m/s,1.1,1.4,1.3,1.3,1.2,1.0,1.3,1.8,...,2.1,1.9,2.2,2.0,2.1,2.3,2.2,2.433333,2.4,2.3
4,Sud-Ouest,m/s,1.4,1.5,1.7,1.6,1.5,1.5,1.6,1.6,...,1.6,1.6,2.0,1.9,1.9,1.7,1.6,1.683333,1.6,1.7

In [126]:
df_soleil.head()

,Région,Units,1996,1997,1998,1999,2000,2001,2002,2003,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Hauts-Bassins,heure,7.9,7.5,7.2,7.2,7.6,7.9,7.8,7.5,...,7.7,7.6,7.3,7.5,8.170959,7.9,8.183333,8.033333,NaN,7.3
1,Boucle du Mouhoun,heure,8.9,8.7,8.3,8.8,8.5,8.8,8.9,8.5,...,8.9,8.7,8.5,8.3,8.553151,8.2,8.508333,8.391667,8.6,8.3
2,Sahel,heure,9.2,8.6,8.4,8.8,9.0,9.3,8.9,8.8,...,8.8,8.7,8.2,8.7,8.615068,8.8,8.783333,8.841667,9.0,NaN
3,Est,heure,8.6,8.2,8.6,NaN,8.4,8.7,8.7,8.5,...,8.4,8.4,8.0,7.8,7.809589,7.7,8.383333,8.316667,8.6,7.9
4,Sud-Ouest,heure,8.2,7.9,8.0,8.6,7.8,8.1,7.9,7.8,...,8.1,7.8,8.1,7.7,NaN,7.7,8.025000,7.866667,7.9,7.7

In [127]:
df_temp.head()

,Région,Units,1996,1997,1998,1999,2000,2001,2002,2003,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Hauts-Bassins,°C,27.65,27.50,27.95,27.30,27.50,28.15,28.40,28.30,...,27.95,28.05,28.10,28.40,27.95,28.195000,28.15,28.25,34.50,27.55
1,Boucle du Mouhoun,°C,29.30,28.85,29.20,28.55,29.15,29.05,29.40,29.20,...,29.30,29.45,29.15,29.85,29.55,29.537500,29.40,29.40,29.75,29.05
2,Sahel,°C,30.00,29.95,29.95,36.90,29.95,29.85,30.05,30.05,...,30.10,30.30,29.80,30.35,29.90,29.958333,30.25,30.05,30.40,NaN
3,Est,°C,28.80,28.80,28.90,28.65,28.60,28.70,28.90,28.90,...,29.25,29.30,29.40,29.55,29.25,29.454167,29.50,29.40,29.65,28.90
4,Sud-Ouest,°C,27.70,27.75,28.15,27.70,27.35,27.65,27.85,28.05,...,27.90,28.00,28.05,28.35,28.05,27.950000,28.25,28.00,28.20,27.55

In [128]:
df_humid.head()

,Région,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Hauts-Bassins,71,72,70,71,70,68,68,70,70,...,74,74,70,71,69.0,72.200000,72,73,73,72.0
1,Boucle du Mouhoun,63,65,65,67,65,64,63,68,67,...,69,68,64,65,65.0,66.666667,67,65,65,67.0
2,Sahel,60,59,61,65,60,58,58,61,59,...,63,60,58,62,62.0,61.583333,60,61,60,NaN
3,Est,67,68,67,70,68,65,66,68,68,...,71,69,63,68,65.0,67.916667,67,67,66,67.0
4,Sud-Ouest,85,81,80,84,83,79,79,82,84,...,82,82,78,78,NaN,78.500000,78,80,83,83.0

At first glance, we notice that there are missing values ​​in the climate databases: number of rainy days, precipitation, wind speed, sunshine, temperatures, and humidity. We will process the missing values ​​in each database. We will check for missing values ​​in the production and area databases.

In [129]:
df_prod.isnull().sum()

Région      0
Céréales    0
Units       0
1996        0
1997        0
1998        0
1999        0
2000        0
2001        0
2002        0
2003        0
2004        0
2005        0
2006        0
2007        0
2008        0
2009        0
2010        0
2011        2
2012        0
2013        0
2014        0
2015        0
2016        0
2017        0
2018        0
2019        0
2020        0
2021        0
2022        0
dtype: int64

In [130]:
df_superf.isnull().sum()

Région      0
Céréales    0
Units       0
1996        0
1997        0
1998        0
1999        0
2000        0
2001        0
2002        0
2003        0
2004        0
2005        0
2006        0
2007        0
2008        0
2009        0
2010        0
2011        1
2012        0
2013        0
2014        0
2015        0
2016        0
2017        0
2018        0
2019        0
2020        0
2021        0
2022        0
dtype: int64

There are two missing values ​​for production in 2011 and one for area in the same year. We will handle them by replacing them with the average of the values ​​in the row to which each missing value belongs.

In [ ]:
#Processing of the production base
# Imputation of NaNs in column '2011' by the average of the corresponding row
def impute_2011(row):
    if pd.isna(row['2011']):
        numeric_vals = row.drop(labels='2011')  # we exclude the '2011' column itself
        numeric_vals = pd.to_numeric(numeric_vals, errors='coerce')  # convert to numeric, ignore strings
        return numeric_vals.mean(skipna=True)
    else:
        return row['2011']

df_prod['2011'] = df_prod.apply(impute_2011, axis=1)

In [132]:
df_prod.isnull().sum()

Région      0
Céréales    0
Units       0
1996        0
1997        0
1998        0
1999        0
2000        0
2001        0
2002        0
2003        0
2004        0
2005        0
2006        0
2007        0
2008        0
2009        0
2010        0
2011        0
2012        0
2013        0
2014        0
2015        0
2016        0
2017        0
2018        0
2019        0
2020        0
2021        0
2022        0
dtype: int64

In [ ]:
#Area datbase treatment
# Imputation of NaNs in column '2011' by the average of the corresponding row
df_superf['2011'] = df_superf.apply(impute_2011, axis=1)
df_superf.isnull().sum()

Région      0
Céréales    0
Units       0
1996        0
1997        0
1998        0
1999        0
2000        0
2001        0
2002        0
2003        0
2004        0
2005        0
2006        0
2007        0
2008        0
2009        0
2010        0
2011        0
2012        0
2013        0
2014        0
2015        0
2016        0
2017        0
2018        0
2019        0
2020        0
2021        0
2022        0
dtype: int64

In [134]:
df_pluie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Région  11 non-null     object
 1   Units   11 non-null     object
 2   1996    8 non-null      float64
 3   1997    8 non-null      float64
 4   1998    8 non-null      float64
 5   1999    8 non-null      float64
 6   2000    8 non-null      float64
 7   2001    8 non-null      float64
 8   2002    8 non-null      float64
 9   2003    8 non-null      float64
 10  2004    8 non-null      float64
 11  2005    8 non-null      float64
 12  2006    9 non-null      float64
 13  2007    9 non-null      float64
 14  2008    9 non-null      float64
 15  2009    9 non-null      float64
 16  2010    10 non-null     float64
 17  2011    10 non-null     float64
 18  2012    10 non-null     float64
 19  2013    10 non-null     float64
 20  2014    10 non-null     float64
 21  2015    11 non-null     int64
 22  2016    11 non-null     int64
 23  2017    11 non-null     int64
 24  2018    11 non-null     int64
 25  2019    11 non-null     int64
 26  2020    11 non-null     int64
 27  2021    11 non-null     int64
 28  2022    10 non-null     float64
dtypes: float64(20), int64(7), object(2)
memory usage: 2.6+ KB

We have a maximum of 11 rows, whereas there are 13 regions in Burkina Faso. This means that some regions have no values ​​at all. Furthermore, there are missing values ​​for these dates. Taking a look at the database, we see, for example, that the Center-East and Center-North regions have no values ​​from 1996 to 2005. Here's how we'll handle the missing values:

* For regions that have at least a certain number of values, we'll perform an imputation using the average of the missing values.
* For regions that don't exist (Cascades and Center-West), we'll create rows for them and process them using a method similar to k-nearest neighbors.
Indeed, the Cascades region is closer to the Hauts-Bassins and Southwest regions. Thus, for each year, the number of rainy days/year corresponding to the Cascades region will be equal to the average of the values ​​for the Hauts-Bassins and the Southwest.
For the Center-West, we will consider the Center, Boucle du Mouhoun, and Center-South as neighbors.

* The Plateau Central region only has values ​​from 2015 to 2022. This is insufficient to perform an average imputation for all other missing values. Therefore, for these missing values, we will take the average of the values ​​for the Center and Center-East regions.

In [ ]:
#Processing missing values ​​from the number of rainy days database.
annees = [str(annee) for annee in range(1996, 2023)]

# 1. Imputation for Centre-East, Centre-North, Sahel: replace NaN year by year
for region in ['Centre-Est', 'Centre-Nord', 'Sahel']:
    idx = df_pluie[df_pluie['Région'] == region].index
    if not idx.empty:
        for annee in annees:
            valeur = df_pluie.loc[idx, annee].values[0]
            # If missing value, impute by the average of other non-missing years in the same region
            if pd.isna(valeur):
                moyenne_autres = df_pluie.loc[idx, annees].mean(axis=1, skipna=True).values[0]
                df_pluie.loc[idx, annee] = moyenne_autres

# 2. Imputation for Plateau Central: average of the values ​​for the Centre and Centre-East regions
idx_pc = df_pluie[df_pluie['Région'] == 'Plateau Central'].index
idx_centre = df_pluie[df_pluie['Région'] == 'Centre'].index
idx_centre_est = df_pluie[df_pluie['Région'] == 'Centre-Est'].index

if not idx_pc.empty and not idx_centre.empty and not idx_centre_est.empty:
    for annee in annees:
        valeur_centre = df_pluie.loc[idx_centre, annee].values[0]
        valeur_centre_est = df_pluie.loc[idx_centre_est, annee].values[0]
        moyenne = (valeur_centre + valeur_centre_est) / 2
        df_pluie.loc[idx_pc, annee] = moyenne

# 3. Create the Cascades modality: average of the Hauts-Bassins and South-West
idx_hauts_bassins = df_pluie[df_pluie['Région'] == 'Hauts-Bassins'].index
idx_sud_ouest = df_pluie[df_pluie['Région'] == 'Sud-Ouest'].index

if not idx_hauts_bassins.empty and not idx_sud_ouest.empty:
    nouvelles_valeurs = {}
    for annee in annees:
        val_hb = df_pluie.loc[idx_hauts_bassins, annee].values[0]
        val_so = df_pluie.loc[idx_sud_ouest, annee].values[0]
        nouvelles_valeurs[annee] = (val_hb + val_so) / 2
    nouvelles_valeurs['Région'] = 'Cascades'
    nouvelles_valeurs['Units'] = df_pluie['Units'].iloc[0]  # retake Units value
    df_pluie = pd.concat([df_pluie, pd.DataFrame([nouvelles_valeurs])], ignore_index=True)

# 4. Create the Centre-West modality: average of the Centre, Boucle du Mouhoun, Centre-Sud
idx_boucle = df_pluie[df_pluie['Région'] == 'Boucle du Mouhoun'].index
idx_centre_sud = df_pluie[df_pluie['Région'] == 'Centre-Sud'].index

if not (idx_centre.empty or idx_boucle.empty or idx_centre_sud.empty):
    nouvelles_valeurs = {}
    for annee in annees:
        val_centre = df_pluie.loc[idx_centre, annee].values[0]
        val_boucle = df_pluie.loc[idx_boucle, annee].values[0]
        val_cs = df_pluie.loc[idx_centre_sud, annee].values[0]
        nouvelles_valeurs[annee] = (val_centre + val_boucle + val_cs) / 3
    nouvelles_valeurs['Région'] = 'Centre-Ouest'
    nouvelles_valeurs['Units'] = df_pluie['Units'].iloc[0]
    df_pluie = pd.concat([df_pluie, pd.DataFrame([nouvelles_valeurs])], ignore_index=True)

# Show result
df_pluie.head()

<ipython-input-135-4d30c695b219>:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '62.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_pluie.loc[idx_pc, annee] = moyenne
<ipython-input-135-4d30c695b219>:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '63.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_pluie.loc[idx_pc, annee] = moyenne
<ipython-input-135-4d30c695b219>:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '60.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_pluie.loc[idx_pc, annee] = moyenne
<ipython-input-135-4d30c695b219>:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '61.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_pluie.loc[idx_pc, annee] = moyenne

,Région,Units,1996,1997,1998,1999,2000,2001,2002,2003,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Hauts-Bassins,Nombre,84.000000,86.000000,93.000000,99.000000,95.000000,87.000000,82.000000,95.000000,...,89.0,101.0,80.0,85.0,76.0,100.0,96.0,88.0,97.0,100.000000
1,Centre-Est,Nombre,53.882353,53.882353,53.882353,53.882353,53.882353,53.882353,53.882353,53.882353,...,48.0,68.0,51.0,62.0,46.0,45.0,48.0,54.0,47.0,55.000000
2,Centre-Nord,Nombre,41.307692,41.307692,41.307692,41.307692,41.307692,41.307692,41.307692,41.307692,...,44.0,46.0,42.0,38.0,29.0,42.0,36.0,42.0,40.0,46.000000
3,Boucle du Mouhoun,Nombre,66.000000,67.000000,75.000000,87.000000,68.000000,73.000000,61.000000,86.000000,...,65.0,76.0,68.0,71.0,68.0,74.0,72.0,76.0,72.0,74.000000
4,Sahel,Nombre,39.000000,52.000000,52.000000,50.000000,48.000000,43.000000,47.000000,56.000000,...,49.0,42.0,42.0,46.0,46.0,49.0,50.0,58.0,48.0,46.730769

In [136]:
#Base precipitations
df_precip.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Région  11 non-null     object
 1   Units   11 non-null     object
 2   1996    8 non-null      float64
 3   1997    8 non-null      float64
 4   1998    8 non-null      float64
 5   1999    8 non-null      float64
 6   2000    8 non-null      float64
 7   2001    8 non-null      float64
 8   2002    8 non-null      float64
 9   2003    8 non-null      float64
 10  2004    8 non-null      float64
 11  2005    8 non-null      float64
 12  2006    9 non-null      float64
 13  2007    9 non-null      float64
 14  2008    9 non-null      float64
 15  2009    9 non-null      float64
 16  2010    10 non-null     float64
 17  2011    10 non-null     float64
 18  2012    10 non-null     float64
 19  2013    10 non-null     float64
 20  2014    10 non-null     float64
 21  2015    11 non-null     float64
 22  2016    11 non-null     float64
 23  2017    11 non-null     float64
 24  2018    11 non-null     float64
 25  2019    11 non-null     float64
 26  2020    11 non-null     float64
 27  2021    11 non-null     float64
 28  2022    10 non-null     float64
dtypes: float64(27), object(2)
memory usage: 2.6+ KB

Precipiations a exactement les mêmes caractéristiques que Nombre de jours de pluie en termes de valeurs manquantes. Donc c'est le même code qui sera appliqué.

In [137]:
#Traitement valeurs manquantes de la base précipitations moyennes annuelles.
annees = [str(annee) for annee in range(1996, 2023)]

# 1. Imputation pour Centre-Est, Centre-Nord, Sahel : remplacer NaN par la moyenne de la ligne (en ignorant les NaN)
for region in ['Centre-Est', 'Centre-Nord', 'Sahel']:
    idx = df_precip[df_precip['Région'] == region].index
    if not idx.empty:
        moyenne_ligne = df_precip.loc[idx, annees].mean(axis=1, skipna=True)
        for annee in annees:
            df_precip.loc[idx, annee] = df_precip.loc[idx, annee].fillna(moyenne_ligne.values[0])

# 2. Imputation pour Plateau Central : moyenne des valeurs des régions Centre et Centre-Est
idx_pc = df_precip[df_precip['Région'] == 'Plateau Central'].index
idx_centre = df_precip[df_precip['Région'] == 'Centre'].index
idx_centre_est = df_precip[df_precip['Région'] == 'Centre-Est'].index

if not idx_pc.empty and not idx_centre.empty and not idx_centre_est.empty:
    for annee in annees:
        valeur_centre = df_precip.loc[idx_centre, annee].values[0]
        valeur_centre_est = df_precip.loc[idx_centre_est, annee].values[0]
        moyenne = (valeur_centre + valeur_centre_est) / 2
        if pd.isna(df_precip.loc[idx_pc, annee].values[0]):
            df_precip.loc[idx_pc, annee] = moyenne

# 3. Créer la modalité Cascades : moyenne des Hauts-Bassins et Sud-Ouest
idx_hauts_bassins = df_precip[df_precip['Région'] == 'Hauts-Bassins'].index
idx_sud_ouest = df_precip[df_precip['Région'] == 'Sud-Ouest'].index

if not idx_hauts_bassins.empty and not idx_sud_ouest.empty:
    nouvelles_valeurs = {}
    for annee in annees:
        val_hb = df_precip.loc[idx_hauts_bassins, annee].values[0]
        val_so = df_precip.loc[idx_sud_ouest, annee].values[0]
        nouvelles_valeurs[annee] = (val_hb + val_so) / 2
    nouvelles_valeurs['Région'] = 'Cascades'
    nouvelles_valeurs['Units'] = df_precip['Units'].iloc[0]  # reprendre la valeur Units
    df_precip = pd.concat([df_precip, pd.DataFrame([nouvelles_valeurs])], ignore_index=True)

# 4. Créer la modalité Centre-Ouest : moyenne des Centre, Boucle du Mouhoun, Centre-Sud
idx_boucle = df_precip[df_precip['Région'] == 'Boucle du Mouhoun'].index
idx_centre_sud = df_precip[df_precip['Région'] == 'Centre-Sud'].index

if not (idx_centre.empty or idx_boucle.empty or idx_centre_sud.empty):
    nouvelles_valeurs = {}
    for annee in annees:
        val_centre = df_precip.loc[idx_centre, annee].values[0]
        val_boucle = df_precip.loc[idx_boucle, annee].values[0]
        val_cs = df_precip.loc[idx_centre_sud, annee].values[0]
        nouvelles_valeurs[annee] = (val_centre + val_boucle + val_cs) / 3
    nouvelles_valeurs['Région'] = 'Centre-Ouest'
    nouvelles_valeurs['Units'] = df_pluie['Units'].iloc[0]
    df_precip = pd.concat([df_precip, pd.DataFrame([nouvelles_valeurs])], ignore_index=True)

# Afficher le résultat
df_precip.head()

,Région,Units,1996,1997,1998,1999,2000,2001,2002,2003,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Hauts-Bassins,mm/an,900.500000,872.900000,1122.900000,1066.200000,1171.700000,924.500000,807.600000,1155.700000,...,936.2,1277.9,1155.4,1190.6,681.7,1320.5,1402.0,1131.5,1219.1,1233.900000
1,Centre-Est,mm/an,868.458824,868.458824,868.458824,868.458824,868.458824,868.458824,868.458824,868.458824,...,642.6,862.1,700.6,1049.6,659.2,725.0,796.5,900.6,836.7,1066.900000
2,Centre-Nord,mm/an,751.223077,751.223077,751.223077,751.223077,751.223077,751.223077,751.223077,751.223077,...,786.0,764.0,708.0,882.0,545.0,933.0,583.0,867.2,611.0,907.000000
3,Boucle du Mouhoun,mm/an,676.000000,837.900000,945.300000,921.900000,580.700000,811.700000,744.800000,986.000000,...,749.2,798.4,1148.2,808.0,865.8,834.8,901.9,826.7,826.8,889.000000
4,Sahel,mm/an,354.100000,532.400000,508.400000,552.000000,356.100000,400.800000,432.900000,753.200000,...,579.3,432.0,530.9,519.2,531.5,493.5,568.9,826.1,557.3,515.211538

In [138]:
#Base vitesse vent
df_vent.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Région  8 non-null      object
 1   Units   8 non-null      object
 2   1996    8 non-null      float64
 3   1997    8 non-null      float64
 4   1998    8 non-null      float64
 5   1999    8 non-null      float64
 6   2000    8 non-null      float64
 7   2001    8 non-null      float64
 8   2002    8 non-null      float64
 9   2003    8 non-null      float64
 10  2004    8 non-null      float64
 11  2005    8 non-null      float64
 12  2006    8 non-null      float64
 13  2007    7 non-null      float64
 14  2008    8 non-null      float64
 15  2009    8 non-null      float64
 16  2010    8 non-null      float64
 17  2011    7 non-null      float64
 18  2012    8 non-null      float64
 19  2013    8 non-null      float64
 20  2014    8 non-null      float64
 21  2015    8 non-null      float64
 22  2016    8 non-null      float64
 23  2017    8 non-null      float64
 24  2018    8 non-null      float64
 25  2019    8 non-null      float64
 26  2020    8 non-null      float64
 27  2021    7 non-null      float64
 28  2022    7 non-null      float64
dtypes: float64(27), object(2)
memory usage: 1.9+ KB

Here, we have a maximum of 8 regions. The missing regions are: Centre-East, Centre-North, Centre-West, Cascades, and Plateau Central.

1. There are some missing values ​​for some regions, which will be processed by imputing the average of the values ​​for that region.
2. Missing regions will be processed by imputing the average of the values ​​for neighboring regions for each year.
Centre.
* Cascades: Average between Hauts-Bassins and Southwest
* Centre-West: Average between Boucle du Mouhoun, Centre, and Centre-South
* Centre-East: Average between Centre and East
* Centre-North: Average between Centre and North
* Plateau Central: Average between Centre and Centre-East

In [139]:
#Traitement valeurs manquantes de la base vitesse moyenne du vent.
annees = [str(an) for an in range(1996, 2023)]

# Imputation des valeurs manquantes pour les régions présentes
for region in df_vent['Région'].unique():
    idx = df_vent[df_vent['Région'] == region].index
    for an in annees:
        if pd.isna(df_vent.loc[idx, an].values[0]):
            # Calculer la moyenne de la région sur les années disponibles
            moyenne_region = df_vent.loc[idx, annees].mean(axis=1).values[0]
            df_vent.loc[idx, an] = moyenne_region

# Créer les nouvelles modalités

# Fonction pour calculer la moyenne entre plusieurs régions
def moyenne_regions(df, regions_source):
    return df[df['Région'].isin(regions_source)][annees].mean()

# Cascades = Moyenne (Hauts-Bassins, Sud-Ouest)
valeurs_cascades = moyenne_regions(df_vent, ['Hauts-Bassins', 'Sud-Ouest'])
df_vent = pd.concat([df_vent, pd.DataFrame({'Région': ['Cascades'], 'Units': ['m/s'], **valeurs_cascades.to_dict()})], ignore_index=True)

# Centre-Ouest = Moyenne (Centre, Boucle du Mouhoun, Centre-Sud)
valeurs_centre_ouest = moyenne_regions(df_vent, ['Centre', 'Boucle du Mouhoun', 'Centre-Sud'])
df_vent = pd.concat([df_vent, pd.DataFrame({'Région': ['Centre-Ouest'], 'Units': ['m/s'], **valeurs_centre_ouest.to_dict()})], ignore_index=True)

# Centre-Est = Moyenne (Centre, Est)
valeurs_centre_est = moyenne_regions(df_vent, ['Centre', 'Est'])
df_vent = pd.concat([df_vent, pd.DataFrame({'Région': ['Centre-Est'], 'Units': ['m/s'], **valeurs_centre_est.to_dict()})], ignore_index=True)

# Centre-Nord = Moyenne (Centre, Nord)
valeurs_centre_nord = moyenne_regions(df_vent, ['Centre', 'Nord'])
df_vent = pd.concat([df_vent, pd.DataFrame({'Région': ['Centre-Nord'], 'Units': ['m/s'], **valeurs_centre_nord.to_dict()})], ignore_index=True)

# Plateau Central = Moyenne (Centre, Centre-Est)
valeurs_plateau_central = moyenne_regions(df_vent, ['Centre', 'Centre-Est'])
df_vent = pd.concat([df_vent, pd.DataFrame({'Région': ['Plateau Central'], 'Units': ['m/s'], **valeurs_plateau_central.to_dict()})], ignore_index=True)

# Visualiser le résultat
df_vent.head()

,Région,Units,1996,1997,1998,1999,2000,2001,2002,2003,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Hauts-Bassins,m/s,3.2,3.3,3.4,2.7,3.1,3.3,3.4,3.1,...,3.1,3.0,3.0,2.9,2.8,2.7,2.8,2.858333,2.8,2.900000
1,Boucle du Mouhoun,m/s,2.3,2.4,2.4,2.6,2.7,2.2,2.1,1.8,...,3.0,2.6,2.7,1.8,1.9,2.3,2.5,2.366667,2.3,2.300000
2,Sahel,m/s,1.4,1.4,1.4,1.2,1.5,1.6,1.5,1.3,...,0.9,0.9,0.9,1.0,1.8,0.9,0.8,0.775000,1.0,1.199038
3,Est,m/s,1.1,1.4,1.3,1.3,1.2,1.0,1.3,1.8,...,2.1,1.9,2.2,2.0,2.1,2.3,2.2,2.433333,2.4,2.300000
4,Sud-Ouest,m/s,1.4,1.5,1.7,1.6,1.5,1.5,1.6,1.6,...,1.6,1.6,2.0,1.9,1.9,1.7,1.6,1.683333,1.6,1.700000

In [140]:
#Base ensoleillement
df_soleil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Région  8 non-null      object
 1   Units   8 non-null      object
 2   1996    8 non-null      float64
 3   1997    8 non-null      float64
 4   1998    8 non-null      float64
 5   1999    7 non-null      float64
 6   2000    8 non-null      float64
 7   2001    8 non-null      float64
 8   2002    8 non-null      float64
 9   2003    8 non-null      float64
 10  2004    8 non-null      float64
 11  2005    8 non-null      float64
 12  2006    8 non-null      float64
 13  2007    8 non-null      float64
 14  2008    8 non-null      float64
 15  2009    8 non-null      float64
 16  2010    8 non-null      float64
 17  2011    8 non-null      float64
 18  2012    8 non-null      float64
 19  2013    8 non-null      float64
 20  2014    8 non-null      float64
 21  2015    8 non-null      float64
 22  2016    8 non-null      float64
 23  2017    6 non-null      float64
 24  2018    8 non-null      float64
 25  2019    8 non-null      float64
 26  2020    8 non-null      float64
 27  2021    7 non-null      float64
 28  2022    7 non-null      float64
dtypes: float64(27), object(2)
memory usage: 1.9+ KB

Sunshine has exactly the same characteristics as Wind Speed ​​in terms of missing values. So the same code will be applied.

In [141]:
#Traitement valeurs manquantes de la base ensoleillement.
annees = [str(an) for an in range(1996, 2023)]

# Imputation des valeurs manquantes pour les régions présentes
for region in df_soleil['Région'].unique():
    idx = df_soleil[df_soleil['Région'] == region].index
    for an in annees:
        if pd.isna(df_soleil.loc[idx, an].values[0]):
            # Calculer la moyenne de la région sur les années disponibles
            moyenne_region = df_soleil.loc[idx, annees].mean(axis=1).values[0]
            df_soleil.loc[idx, an] = moyenne_region

# Créer les nouvelles modalités

# Fonction pour calculer la moyenne entre plusieurs régions
def moyenne_regions(df, regions_source):
    return df[df['Région'].isin(regions_source)][annees].mean()

# Cascades = Moyenne (Hauts-Bassins, Sud-Ouest)
valeurs_cascades = moyenne_regions(df_soleil, ['Hauts-Bassins', 'Sud-Ouest'])
df_soleil = pd.concat([df_soleil, pd.DataFrame({'Région': ['Cascades'], 'Units': ['m/s'], **valeurs_cascades.to_dict()})], ignore_index=True)

# Centre-Ouest = Moyenne (Centre, Boucle du Mouhoun, Centre-Sud)
valeurs_centre_ouest = moyenne_regions(df_soleil, ['Centre', 'Boucle du Mouhoun', 'Centre-Sud'])
df_soleil = pd.concat([df_soleil, pd.DataFrame({'Région': ['Centre-Ouest'], 'Units': ['m/s'], **valeurs_centre_ouest.to_dict()})], ignore_index=True)

# Centre-Est = Moyenne (Centre, Est)
valeurs_centre_est = moyenne_regions(df_soleil, ['Centre', 'Est'])
df_soleil = pd.concat([df_soleil, pd.DataFrame({'Région': ['Centre-Est'], 'Units': ['m/s'], **valeurs_centre_est.to_dict()})], ignore_index=True)

# Centre-Nord = Moyenne (Centre, Nord)
valeurs_centre_nord = moyenne_regions(df_soleil, ['Centre', 'Nord'])
df_soleil = pd.concat([df_soleil, pd.DataFrame({'Région': ['Centre-Nord'], 'Units': ['m/s'], **valeurs_centre_nord.to_dict()})], ignore_index=True)

# Plateau Central = Moyenne (Centre, Centre-Est)
valeurs_plateau_central = moyenne_regions(df_soleil, ['Centre', 'Centre-Est'])
df_soleil = pd.concat([df_soleil, pd.DataFrame({'Région': ['Plateau Central'], 'Units': ['m/s'], **valeurs_plateau_central.to_dict()})], ignore_index=True)

# Visualiser le résultat
df_soleil.head()

,Région,Units,1996,1997,1998,1999,2000,2001,2002,2003,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Hauts-Bassins,heure,7.9,7.5,7.2,7.200000,7.6,7.9,7.8,7.5,...,7.7,7.6,7.3,7.5,8.170959,7.9,8.183333,8.033333,7.526447,7.300000
1,Boucle du Mouhoun,heure,8.9,8.7,8.3,8.800000,8.5,8.8,8.9,8.5,...,8.9,8.7,8.5,8.3,8.553151,8.2,8.508333,8.391667,8.600000,8.300000
2,Sahel,heure,9.2,8.6,8.4,8.800000,9.0,9.3,8.9,8.8,...,8.8,8.7,8.2,8.7,8.615068,8.8,8.783333,8.841667,9.000000,8.655387
3,Est,heure,8.6,8.2,8.6,8.234984,8.4,8.7,8.7,8.5,...,8.4,8.4,8.0,7.8,7.809589,7.7,8.383333,8.316667,8.600000,7.900000
4,Sud-Ouest,heure,8.2,7.9,8.0,8.600000,7.8,8.1,7.9,7.8,...,8.1,7.8,8.1,7.7,7.834295,7.7,8.025000,7.866667,7.900000,7.700000

In [142]:
#Base température
df_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Région  8 non-null      object
 1   Units   8 non-null      object
 2   1996    8 non-null      float64
 3   1997    8 non-null      float64
 4   1998    8 non-null      float64
 5   1999    8 non-null      float64
 6   2000    8 non-null      float64
 7   2001    8 non-null      float64
 8   2002    8 non-null      float64
 9   2003    8 non-null      float64
 10  2004    8 non-null      float64
 11  2005    8 non-null      float64
 12  2006    8 non-null      float64
 13  2007    8 non-null      float64
 14  2008    8 non-null      float64
 15  2009    8 non-null      float64
 16  2010    8 non-null      float64
 17  2011    8 non-null      float64
 18  2012    8 non-null      float64
 19  2013    8 non-null      float64
 20  2014    8 non-null      float64
 21  2015    8 non-null      float64
 22  2016    8 non-null      float64
 23  2017    8 non-null      float64
 24  2018    8 non-null      float64
 25  2019    8 non-null      float64
 26  2020    8 non-null      float64
 27  2021    8 non-null      float64
 28  2022    7 non-null      float64
dtypes: float64(27), object(2)
memory usage: 1.9+ KB

Temperatures has exactly the same characteristics as Wind Speed ​​in terms of missing values. So the same code will be applied.

In [143]:
#Traitement valeurs manquantes de la base températures.
annees = [str(an) for an in range(1996, 2023)]

# Imputation des valeurs manquantes pour les régions présentes
for region in df_temp['Région'].unique():
    idx = df_temp[df_temp['Région'] == region].index
    for an in annees:
        if pd.isna(df_temp.loc[idx, an].values[0]):
            # Calculer la moyenne de la région sur les années disponibles
            moyenne_region = df_temp.loc[idx, annees].mean(axis=1).values[0]
            df_temp.loc[idx, an] = moyenne_region

# Créer les nouvelles modalités

# Fonction pour calculer la moyenne entre plusieurs régions
def moyenne_regions(df, regions_source):
    return df[df['Région'].isin(regions_source)][annees].mean()

# Cascades = Moyenne (Hauts-Bassins, Sud-Ouest)
valeurs_cascades = moyenne_regions(df_temp, ['Hauts-Bassins', 'Sud-Ouest'])
df_temp = pd.concat([df_temp, pd.DataFrame({'Région': ['Cascades'], 'Units': ['m/s'], **valeurs_cascades.to_dict()})], ignore_index=True)

# Centre-Ouest = Moyenne (Centre, Boucle du Mouhoun, Centre-Sud)
valeurs_centre_ouest = moyenne_regions(df_temp, ['Centre', 'Boucle du Mouhoun', 'Centre-Sud'])
df_temp = pd.concat([df_temp, pd.DataFrame({'Région': ['Centre-Ouest'], 'Units': ['m/s'], **valeurs_centre_ouest.to_dict()})], ignore_index=True)

# Centre-Est = Moyenne (Centre, Est)
valeurs_centre_est = moyenne_regions(df_temp, ['Centre', 'Est'])
df_temp = pd.concat([df_temp, pd.DataFrame({'Région': ['Centre-Est'], 'Units': ['m/s'], **valeurs_centre_est.to_dict()})], ignore_index=True)

# Centre-Nord = Moyenne (Centre, Nord)
valeurs_centre_nord = moyenne_regions(df_temp, ['Centre', 'Nord'])
df_temp = pd.concat([df_temp, pd.DataFrame({'Région': ['Centre-Nord'], 'Units': ['m/s'], **valeurs_centre_nord.to_dict()})], ignore_index=True)

# Plateau Central = Moyenne (Centre, Centre-Est)
valeurs_plateau_central = moyenne_regions(df_temp, ['Centre', 'Centre-Est'])
df_temp = pd.concat([df_temp, pd.DataFrame({'Région': ['Plateau Central'], 'Units': ['m/s'], **valeurs_plateau_central.to_dict()})], ignore_index=True)

# Visualiser le résultat
df_temp.head()

,Région,Units,1996,1997,1998,1999,2000,2001,2002,2003,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Hauts-Bassins,°C,27.65,27.50,27.95,27.30,27.50,28.15,28.40,28.30,...,27.95,28.05,28.10,28.40,27.95,28.195000,28.15,28.25,34.50,27.550000
1,Boucle du Mouhoun,°C,29.30,28.85,29.20,28.55,29.15,29.05,29.40,29.20,...,29.30,29.45,29.15,29.85,29.55,29.537500,29.40,29.40,29.75,29.050000
2,Sahel,°C,30.00,29.95,29.95,36.90,29.95,29.85,30.05,30.05,...,30.10,30.30,29.80,30.35,29.90,29.958333,30.25,30.05,30.40,30.369551
3,Est,°C,28.80,28.80,28.90,28.65,28.60,28.70,28.90,28.90,...,29.25,29.30,29.40,29.55,29.25,29.454167,29.50,29.40,29.65,28.900000
4,Sud-Ouest,°C,27.70,27.75,28.15,27.70,27.35,27.65,27.85,28.05,...,27.90,28.00,28.05,28.35,28.05,27.950000,28.25,28.00,28.20,27.550000

In [144]:
#Base humidité
df_humid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 28 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Région  8 non-null      object
 1   1996    8 non-null      int64
 2   1997    8 non-null      int64
 3   1998    8 non-null      int64
 4   1999    8 non-null      int64
 5   2000    8 non-null      int64
 6   2001    8 non-null      int64
 7   2002    8 non-null      int64
 8   2003    8 non-null      int64
 9   2004    8 non-null      int64
 10  2005    8 non-null      int64
 11  2006    8 non-null      int64
 12  2007    8 non-null      int64
 13  2008    8 non-null      int64
 14  2009    8 non-null      int64
 15  2010    8 non-null      int64
 16  2011    8 non-null      int64
 17  2012    8 non-null      int64
 18  2013    8 non-null      int64
 19  2014    8 non-null      int64
 20  2015    8 non-null      int64
 21  2016    8 non-null      int64
 22  2017    6 non-null      float64
 23  2018    8 non-null      float64
 24  2019    8 non-null      int64
 25  2020    8 non-null      int64
 26  2021    8 non-null      int64
 27  2022    7 non-null      float64
dtypes: float64(3), int64(24), object(1)
memory usage: 1.9+ KB

Humidity has exactly the same characteristics as Wind Speed ​​in terms of missing values. So the same code will be applied.

In [145]:
#Traitement valeurs manquantes de la base humidité.
annees = [str(an) for an in range(1996, 2023)]

# Imputation des valeurs manquantes pour les régions présentes
for region in df_humid['Région'].unique():
    idx = df_humid[df_humid['Région'] == region].index
    for an in annees:
        if pd.isna(df_humid.loc[idx, an].values[0]):
            # Calculer la moyenne de la région sur les années disponibles
            moyenne_region = df_humid.loc[idx, annees].mean(axis=1).values[0]
            df_humid.loc[idx, an] = moyenne_region

# Créer les nouvelles modalités

# Fonction pour calculer la moyenne entre plusieurs régions
def moyenne_regions(df, regions_source):
    return df[df['Région'].isin(regions_source)][annees].mean()

# Cascades = Moyenne (Hauts-Bassins, Sud-Ouest)
valeurs_cascades = moyenne_regions(df_humid, ['Hauts-Bassins', 'Sud-Ouest'])
df_humid = pd.concat([df_humid, pd.DataFrame({'Région': ['Cascades'], 'Units': ['m/s'], **valeurs_cascades.to_dict()})], ignore_index=True)

# Centre-Ouest = Moyenne (Centre, Boucle du Mouhoun, Centre-Sud)
valeurs_centre_ouest = moyenne_regions(df_humid, ['Centre', 'Boucle du Mouhoun', 'Centre-Sud'])
df_humid = pd.concat([df_humid, pd.DataFrame({'Région': ['Centre-Ouest'], 'Units': ['m/s'], **valeurs_centre_ouest.to_dict()})], ignore_index=True)

# Centre-Est = Moyenne (Centre, Est)
valeurs_centre_est = moyenne_regions(df_humid, ['Centre', 'Est'])
df_humid = pd.concat([df_humid, pd.DataFrame({'Région': ['Centre-Est'], 'Units': ['m/s'], **valeurs_centre_est.to_dict()})], ignore_index=True)

# Centre-Nord = Moyenne (Centre, Nord)
valeurs_centre_nord = moyenne_regions(df_humid, ['Centre', 'Nord'])
df_humid = pd.concat([df_humid, pd.DataFrame({'Région': ['Centre-Nord'], 'Units': ['m/s'], **valeurs_centre_nord.to_dict()})], ignore_index=True)

# Plateau Central = Moyenne (Centre, Centre-Est)
valeurs_plateau_central = moyenne_regions(df_humid, ['Centre', 'Centre-Est'])
df_humid = pd.concat([df_humid, pd.DataFrame({'Région': ['Plateau Central'], 'Units': ['m/s'], **valeurs_plateau_central.to_dict()})], ignore_index=True)

# Visualiser le résultat
df_humid.head()

,Région,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,Units
0,Hauts-Bassins,71.0,72.0,70.0,71.0,70.0,68.0,68.0,70.0,70.0,...,74.0,70.0,71.0,69.000000,72.200000,72.0,73.0,73.0,72.000000,NaN
1,Boucle du Mouhoun,63.0,65.0,65.0,67.0,65.0,64.0,63.0,68.0,67.0,...,68.0,64.0,65.0,65.000000,66.666667,67.0,65.0,65.0,67.000000,NaN
2,Sahel,60.0,59.0,61.0,65.0,60.0,58.0,58.0,61.0,59.0,...,60.0,58.0,62.0,62.000000,61.583333,60.0,61.0,60.0,60.330128,NaN
3,Est,67.0,68.0,67.0,70.0,68.0,65.0,66.0,68.0,68.0,...,69.0,63.0,68.0,65.000000,67.916667,67.0,67.0,66.0,67.000000,NaN
4,Sud-Ouest,85.0,81.0,80.0,84.0,83.0,79.0,79.0,82.0,84.0,...,82.0,78.0,78.0,81.057692,78.500000,78.0,80.0,83.0,83.000000,NaN

Now that the databases have been processed, we'll move on to merging them into a single database. For each database, we'll transform them by putting the years in a Year column, create a column for the information provided by the database (Production, Area, Average Annual Precipitation, Temperature, etc.), and sort by region and grain if there's a grain and year column.
Then the next transformed database will be merged with the previous one. After merging the Production and Area databases, we'll create a new Yield variable.

In [ ]:
# Transformation of the production base:
#Removal of unnecessary Burkina lines
df_prod = df_prod[df_prod['Région'] != 'Burkina Faso']

#owe convert the year columns into rows
df_prod_trans = pd.melt(df_prod,
                  id_vars=['Région', 'Céréales'],  # We keep these columns fixed
                  var_name='Année',
                  value_name='Production (en tonnes)')

df_prod_trans = df_prod_trans[df_prod_trans['Année'].str.isnumeric()]
# Convert Year to int
df_prod_trans['Année'] = df_prod_trans['Année'].astype(int)

# Sort: Region ➔ Type of cereal ➔ Year
df_prod_trans = df_prod_trans.sort_values(by=['Région', 'Céréales', 'Année'])

print(df_prod_trans.head())

                Région  Céréales  Année Production (en tonnes)
91   Boucle du Mouhoun  Arachide   1996                  14810
182  Boucle du Mouhoun  Arachide   1997                  22231
273  Boucle du Mouhoun  Arachide   1998                  15490
364  Boucle du Mouhoun  Arachide   1999                  17127
455  Boucle du Mouhoun  Arachide   2000                  21565

In [147]:
# Transformer la base Superficie
#Suppression des lignes Burkina qui ne sont pas necessaires
df_superf = df_superf[df_superf['Région'] != 'Burkina Faso']

#on convertit les colonnes années en lignes
df_superf_trans = pd.melt(df_superf,
                             id_vars=['Région', 'Céréales'],
                             var_name='Année',
                             value_name='Superficie (en ha)')
df_superf_trans = df_superf_trans[df_superf_trans['Année'].str.isnumeric()]
df_superf_trans = df_superf_trans.sort_values(by=['Région', 'Céréales', 'Année'])
df_superf_trans['Année'] = df_superf_trans['Année'].astype(int)
# Fusionner les deux bases
df_final1 = pd.merge(df_prod_trans,
                    df_superf_trans,
                    on=['Région', 'Céréales', 'Année'],
                    how='inner')

print(df_final1.head())

              Région  Céréales  Année Production (en tonnes)  \
0  Boucle du Mouhoun  Arachide   1996                  14810
1  Boucle du Mouhoun  Arachide   1997                  22231
2  Boucle du Mouhoun  Arachide   1998                  15490
3  Boucle du Mouhoun  Arachide   1999                  17127
4  Boucle du Mouhoun  Arachide   2000                  21565

  Superficie (en ha)
0              37458
1              21702
2              30410
3              21862
4              26072

In [148]:
# Fonction pour calculer le rendement avec un if
def calcul_rendement(row):
    if row['Superficie (en ha)'] > 0 and row['Production (en tonnes)'] > 0:
        return round(row['Production (en tonnes)'] / row['Superficie (en ha)'], 3)
    elif row['Superficie (en ha)'] >= 0 and row['Production (en tonnes)'] == 0:
        return 0
    else:
        return 'N.A.'

# Appliquer la fonction ligne par ligne
df_final1['Rendement (tonne/ha)'] = df_final1.apply(calcul_rendement, axis=1)


print(df_final1.head())

              Région  Céréales  Année Production (en tonnes)  \
0  Boucle du Mouhoun  Arachide   1996                  14810
1  Boucle du Mouhoun  Arachide   1997                  22231
2  Boucle du Mouhoun  Arachide   1998                  15490
3  Boucle du Mouhoun  Arachide   1999                  17127
4  Boucle du Mouhoun  Arachide   2000                  21565

  Superficie (en ha) Rendement (tonne/ha)
0              37458                0.395
1              21702                1.024
2              30410                0.509
3              21862                0.783
4              26072                0.827

In [149]:
# Transformer la base precipitation: années en colonne
df_precip_trans = pd.melt(df_precip,
                         id_vars=['Région'],  # on garde la colonne Région
                         var_name='Année',
                         value_name='Précipitations moyennes annuelles (en mm)')

# Nettoyer colonne Année
df_precip_trans = df_precip_trans[df_precip_trans['Année'].str.isnumeric()]
df_precip_trans['Année'] = df_precip_trans['Année'].astype(int)

# Trier par Région et Année
df_precip_trans = df_precip_trans.sort_values(by=['Région', 'Année']).reset_index(drop=True)

# Fusionner avec df.final1
df_final2 = pd.merge(df_final1,
                           df_precip_trans,
                           on=['Région', 'Année'],
                           how='left')  # on conserve toutes les lignes de df.final

# Trier aussi la base finale
df_final2 = df_final2.sort_values(by=['Région', 'Céréales', 'Année']).reset_index(drop=True)

In [150]:
# Transformer la base jour de pluies: années en colonne
df_pluie_trans = pd.melt(df_pluie,
                         id_vars=['Région'],  # on garde la colonne Région
                         var_name='Année',
                         value_name='Nombre de jours de pluie ')

# Nettoyer colonne Année
df_pluie_trans = df_pluie_trans[df_pluie_trans['Année'].str.isnumeric()]
df_pluie_trans['Année'] = df_pluie_trans['Année'].astype(int)

# Trier par Région et Année
df_pluie_trans = df_pluie_trans.sort_values(by=['Région', 'Année']).reset_index(drop=True)

# Fusionner avec df.final2
df_final3 = pd.merge(df_final2,
                           df_pluie_trans,
                           on=['Région', 'Année'],
                           how='left')  # on conserve toutes les lignes de df.final2

# Trier aussi la base finale
df_final3 = df_final3.sort_values(by=['Région', 'Céréales', 'Année']).reset_index(drop=True)

In [151]:
# Transformer la base température: années en colonne
df_temp_trans = pd.melt(df_temp,
                         id_vars=['Région'],  # on garde la colonne Région
                         var_name='Année',
                         value_name='Températures moyennes annuelles (en C°)')

# Nettoyer colonne Année
df_temp_trans = df_temp_trans[df_temp_trans['Année'].str.isnumeric()]
df_temp_trans['Année'] = df_temp_trans['Année'].astype(int)

# Trier par Région et Année
df_temp_trans = df_temp_trans.sort_values(by=['Région', 'Année']).reset_index(drop=True)

# Fusionner avec df.final3
df_final4 = pd.merge(df_final3,
                           df_temp_trans,
                           on=['Région', 'Année'],
                           how='left')  # on conserve toutes les lignes de df.final3

# Trier aussi la base finale
df_final4 = df_final4.sort_values(by=['Région', 'Céréales', 'Année']).reset_index(drop=True)

In [152]:
# Transformer la base humidité: années en colonne
df_humid_trans = pd.melt(df_humid,
                         id_vars=['Région'],  # on garde la colonne Région
                         var_name='Année',
                         value_name='Humidité relative maximale (en %)')

# Nettoyer colonne Année
df_humid_trans = df_humid_trans[df_humid_trans['Année'].str.isnumeric()]
df_humid_trans['Année'] = df_humid_trans['Année'].astype(int)

# Trier par Région et Année
df_humid_trans = df_humid_trans.sort_values(by=['Région', 'Année']).reset_index(drop=True)

# Fusionner avec df.final4
df_final5 = pd.merge(df_final4,
                           df_humid_trans,
                           on=['Région', 'Année'],
                           how='left')  # on conserve toutes les lignes de df.final4

# Trier aussi la base finale
df_final5 = df_final5.sort_values(by=['Région', 'Céréales', 'Année']).reset_index(drop=True)

In [153]:
# Transformer la base vent: années en colonne
df_vent_trans = pd.melt(df_vent,
                         id_vars=['Région'],  # on garde la colonne Région
                         var_name='Année',
                         value_name='Vent moyen annuel (en m/s)')

# Nettoyer colonne Année
df_vent_trans = df_vent_trans[df_vent_trans['Année'].str.isnumeric()]
df_vent_trans['Année'] = df_vent_trans['Année'].astype(int)

# Trier par Région et Année
df_vent_trans = df_vent_trans.sort_values(by=['Région', 'Année']).reset_index(drop=True)

# Fusionner avec df.final5
df_final6 = pd.merge(df_final5,
                           df_vent_trans,
                           on=['Région', 'Année'],
                           how='left')  # on conserve toutes les lignes de df.final5

# Trier aussi la base finale
df_final6 = df_final6.sort_values(by=['Région', 'Céréales', 'Année']).reset_index(drop=True)

In [154]:
# Transformer la base ensoleillement: années en colonne
df_soleil_trans = pd.melt(df_soleil,
                         id_vars=['Région'],  # on garde la colonne Région
                         var_name='Année',
                         value_name='Durée ensoleillement (en h/jr)')

# Nettoyer colonne Année
df_soleil_trans = df_soleil_trans[df_soleil_trans['Année'].str.isnumeric()]
df_soleil_trans['Année'] = df_soleil_trans['Année'].astype(int)

# Trier par Région et Année
df_soleil_trans = df_soleil_trans.sort_values(by=['Région', 'Année']).reset_index(drop=True)

# Fusionner avec df.final6
df_final = pd.merge(df_final6,
                           df_soleil_trans,
                           on=['Région', 'Année'],
                           how='left')  # on conserve toutes les lignes de df.final6

# Trier aussi la base finale p
df_final = df_final.sort_values(by=['Région', 'Céréales', 'Année']).reset_index(drop=True)

In [155]:
df_final.isnull().sum()

Région                                       0
Céréales                                     0
Année                                        0
Production (en tonnes)                       0
Superficie (en ha)                           0
Rendement (tonne/ha)                         0
Précipitations moyennes annuelles (en mm)    0
Nombre de jours de pluie                     0
Températures moyennes annuelles (en C°)      0
Humidité relative maximale (en %)            0
Vent moyen annuel (en m/s)                   0
Durée ensoleillement (en h/jr)               0
dtype: int64

In [157]:
# Sauvegarder la base finale
df_final.to_excel('base_finale_céréales.xlsx', index=False)

from google.colab import drive

# Monter Google Drive
drive.mount('/content/drive')

# Copier le fichier vers ton Google Drive (dossier "Mon Drive")
!cp base_finale_céréales.xlsx /content/drive/MyDrive/

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).